name: flutter_app_pay
description: >
  Modular in-app purchase SDK for Flutter.
  Provides a unified API for Google Play, App Store, and RuStore billing
  through separate provider plugins. Includes entitlement management,
  server-side receipt verification hooks, and a simple extensible design.
version: 0.0.3
homepage: https://github.com/Kotelnikovekb/flutter_app_pay
repository: https://github.com/Kotelnikovekb/flutter_app_pay
issue_tracker: https://github.com/Kotelnikovekb/flutter_app_pay/issues

topics:
  - in-app-purchase
  - subscriptions
  - payments
  - google-play
  - app-store

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_app_pay_api: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
